services:
  mongodb:
    image: mongo:latest
    container_name: cozy_mongodb
    ports:
      - "27017:27017"
    networks:
      - cozy_network

  prometheus:
    image: prom/prometheus:latest
    container_name: cozy_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./scrape_configs/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - cozy_network

  grafana:
    image: grafana/grafana:latest
    container_name: cozy_grafana
    ports:
      - "3000:3000"
    networks:
      - cozy_network

networks:
  cozy_network:
    driver: bridge